### ISSUE TITLE
How can the model be trained without sequences being padded?

### ISSUE THREAD

**Issue by tianylin98** [airalcorn2/Deep-Semantic-Similarity-Model#10]
I have trouble understanding this fitting process:

```python
for i in range(sample_size):
        history = model.fit([l_Qs[i], pos_l_Ds[i]] + [neg_l_Ds[j][i] for j in range(J)], y, epochs = 1, verbose = 0)
```
where each of the training sample goes through the network only once. I don't think it is applicable.

On the other hand, I don't think using a padded input is applicable, either. It just doesn't match the original method. Could someone give me some advice on how to deal with variable inputs (in the paper)?

**Comment by airalcorn2** [comment]
You can pass each training sample through the network [as many times as you want](https://github.com/keras-team/keras/issues/4446#issuecomment-261804574).
