### ISSUE TITLE
For text match problem, what is the different between question-question match and question-answer match? 

### ISSUE THREAD

**Issue by guotong1988** [airalcorn2/Deep-Semantic-Similarity-Model#11]
I know question-question match is a text similarity problem.
What about question-answer match or question-doc match? It is used in information retrieval.

Thank you!!

**Comment by airalcorn2** [comment]
This is not the forum for general knowledge questions. I recommend searching the internet (e.g., a query of "question answering machine learning tutorial" had [this](https://people.cs.umass.edu/~miyyer/data/deepqa.pdf) in the results).
