### ISSUE TITLE
why neg_l_Ds are derived from pos_l_Ds?

### ISSUE THREAD

**Issue by xxxxxxxxy** [airalcorn2/Deep-Semantic-Similarity-Model#12]
`neg_l_Ds = [[] for j in range(J)]
for i in range(sample_size):
    possibilities = list(range(sample_size))
    possibilities.remove(i)
    negatives = np.random.choice(possibilities, J, replace = False)
    for j in range(J):
        negative = negatives[j]
        neg_l_Ds[j].append(pos_l_Ds[negative])
`
I think negative sample is not the corresponding search result. So why neg_l_Ds are derived from pos_l_Ds?

**Comment by airalcorn2** [comment]
This is just dummy data, but `pos_l_Ds` is a list of positive documents corresponding to the queries in `l_Qs`, i.e., the positive document for `l_Qs[i]` is `pos_l_Ds[i]`. As a result, given a particularly query `l_Qs[i]`, all of the documents in `pos_l_Ds` except `pos_l_Ds[i]` can be used as negative documents.
