### ISSUE TITLE
Shared weights

### ISSUE THREAD

**Issue by michellemay** [airalcorn2/Deep-Semantic-Similarity-Model#2]
Hi, I stumbled upon your implementation of dssm and was wondering the following: should the different weights matrices be shared between query and doc?

**Comment by airalcorn2** [comment]
See the last couple of paragraphs in section 5.2 of [this paper](https://www.microsoft.com/en-us/research/publication/a-latent-semantic-model-with-convolutional-pooling-structure-for-information-retrieval/). You can share the weights if you want, but the authors say using separate nets for the query and documents gives better performance.

**Comment by michellemay** [comment]
Indeed, I missed that line.  Thanks.
