### ISSUE TITLE
How to actually view the similarity score in the end?

### ISSUE THREAD

**Issue by Pranav-Goel** [airalcorn2/Deep-Semantic-Similarity-Model#3]
Hello sir

I have been working on implementing DSSM and CDSSM for a while now. Your code is excellent, easy to understand and the comments help to follow it in perfect sync with the paper.
The entire code is running. However, I wanted to see the value of R_Q_D_p or R_Q_D_ns in the end, and could not to do that. Backend's eval function gives an error, and I am unable to view the actual score inside the tensor.

I would be grateful if you could tell how to view the value/scores.

Once again, I really appreciate your efforts and well-written code!

**Comment by Pranav-Goel** [comment]
For reference, this is the error that comes up when I run print(backend.eval(R_Q_D_p)) - 

InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by airalcorn2** [comment]
@Pranav-Goel - thanks for the kind words. To retrieve similarity scores, you need to use the [`get_R_Q_D_p`](https://github.com/airalcorn2/Deep-Semantic-Similarity-Model/blob/master/deep_semantic_similarity_keras.py#L165) function at the bottom of the source code. For example, `get_R_Q_D_p([l_Qs, pos_l_Ds])` will return the similarity scores for all of the queries and documents in the data set.

**Comment by Pranav-Goel** [comment]
Thank you so much for replying. 
I was thinking that R_Q_D_p would contain the output tensor and I can get the score from that. Did not think of running the function with inputs.
Thanks for your time :)
