### ISSUE TITLE
Example Please?

### ISSUE THREAD

**Issue by budhiraja** [airalcorn2/Deep-Semantic-Similarity-Model#6]
Hey.. Can an example be provided on how to train the network and then use it for a pair of documents? Thanks!

**Comment by airalcorn2** [comment]
My code demonstrates [how to train the model with dummy data](https://github.com/airalcorn2/Deep-Semantic-Similarity-Model/blob/master/deep_semantic_similarity_keras.py#L101) and also [how to calculate the cosine similarity between the semantic representations of a query and a document](https://github.com/airalcorn2/Deep-Semantic-Similarity-Model/blob/master/deep_semantic_similarity_keras.py#L154). See my response [here](https://github.com/airalcorn2/Deep-Semantic-Similarity-Model/issues/5#issuecomment-306053271) for why I don't provide real data.
