### ISSUE TITLE
Does it work for one-hot vector?

### ISSUE THREAD

**Issue by fallcat** [airalcorn2/Deep-Semantic-Similarity-Model#7]
Hi! Thank you for making this code! I'm studying CDSSM and trying to import dataset in. I'm new to this so I'm a little confused, so sorry if this question is too easy. If I port data from a dataset, should it be in an array of one-hot vectors?

**Comment by airalcorn2** [comment]
See section 3.2 of the [paper](http://research.microsoft.com/pubs/226585/cikm2014_cdssm_final.pdf). They convert each word to a "letter-trigram vector" and then use those to build n-gram vectors. You can use whatever vector representation of words you want, though (e.g., `word2vec` vectors or one-hot vectors).
